// The descriptor names under MeSH tree Z01 (Geographic Locations), read from the NLM MeSH
// SPARQL endpoint (id.nlm.nih.gov/mesh). MeSH indexes a study by where it ran with these, so
// a MeSH keyword list carries them beside its subject headings (#3685).
const MESH_GEOGRAPHIC_DESCRIPTOR_NAMES = [
  'Afghanistan',
  'Africa',
  'Africa South of the Sahara',
  'Africa, Central',
  'Africa, Eastern',
  'Africa, Northern',
  'Africa, Southern',
  'Africa, Western',
  'Alabama',
  'Alaska',
  'Albania',
  'Alberta',
  'Algeria',
  'American Samoa',
  'Americas',
  'Ancient Lands',
  'Andorra',
  'Angola',
  'Antarctic Regions',
  'Antigua and Barbuda',
  'Appalachian Region',
  'Arabia',
  'Arctic Regions',
  'Argentina',
  'Arizona',
  'Arkansas',
  'Armenia',
  'Aruba',
  'Asia',
  'Asia, Central',
  'Asia, Eastern',
  'Asia, Northern',
  'Asia, Southeastern',
  'Asia, Southern',
  'Asia, Western',
  'Atlantic Islands',
  'Atlantic Ocean',
  'Australasia',
  'Australia',
  'Australian Capital Territory',
  'Austria',
  'Austria-Hungary',
  'Azerbaijan',
  'Azores',
  'Bahamas',
  'Bahrain',
  'Balkan Peninsula',
  'Baltic States',
  'Baltimore',
  'Bangladesh',
  'Barbados',
  'Bashkiria',
  'Beijing',
  'Belgium',
  'Belize',
  'Benin',
  'Berlin',
  'Bermuda',
  'Bhutan',
  'Black Sea',
  'Bolivia',
  'Borneo',
  'Bosnia and Herzegovina',
  'Boston',
  'Botswana',
  'Brazil',
  'British Columbia',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Byzantium',
  'Cabo Verde',
  'California',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Caribbean Netherlands',
  'Caribbean Region',
  'Central African Republic',
  'Central America',
  'Chad',
  'Channel Islands',
  'Chicago',
  'Chile',
  'China',
  'Cities',
  'Colombia',
  'Colorado',
  'Commonwealth of Independent States',
  'Comoros',
  'Confederate States of America',
  'Congo',
  'Connecticut',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czech Republic',
  'Czechoslovakia',
  'Dagestan',
  'Delaware',
  "Democratic People's Republic of Korea",
  'Democratic Republic of the Congo',
  'Denmark',
  'District of Columbia',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'Egypt, Ancient',
  'El Salvador',
  'England',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Europe',
  'Europe, Eastern',
  'European Alpine Region',
  'Falkland Islands',
  'Fiji',
  'Finland',
  'Florida',
  'France',
  'French Guiana',
  'Gabon',
  'Gambia',
  'Geographic Locations',
  'Georgia',
  'Georgia (Republic)',
  'Germany',
  'Germany, East',
  'Germany, West',
  'Ghana',
  'Gibraltar',
  'Great Lakes Region',
  'Greece',
  'Greece, Ancient',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Gulf of America',
  'Guyana',
  'Haiti',
  'Hawaii',
  'Hebrides',
  'Himalayas',
  'Historical Geographic Locations',
  'Holy Roman Empire',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'Idaho',
  'Illinois',
  'Independent State of Samoa',
  'India',
  'Indian Ocean',
  'Indian Ocean Islands',
  'Indiana',
  'Indochina',
  'Indonesia',
  'Iowa',
  'Iran',
  'Iraq',
  'Ireland',
  'Islands',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kansas',
  'Kazakhstan',
  'Kentucky',
  'Kenya',
  'Kiribati',
  'Korea',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latin America',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'London',
  'Los Angeles',
  'Louisiana',
  'Luxembourg',
  'Macau',
  'Madagascar',
  'Maine',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Manitoba',
  'Martinique',
  'Maryland',
  'Massachusetts',
  'Mauritania',
  'Mauritius',
  'Mediterranean Islands',
  'Mediterranean Region',
  'Mediterranean Sea',
  'Mekong Valley',
  'Melanesia',
  'Mesopotamia',
  'Mexico',
  'Michigan',
  'Micronesia',
  'Mid-Atlantic Region',
  'Middle East',
  'Midwestern United States',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montana',
  'Montenegro',
  'Morocco',
  'Moscow',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nebraska',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'Nevada',
  'New Brunswick',
  'New Caledonia',
  'New England',
  'New Guinea',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New Orleans',
  'New South Wales',
  'New York',
  'New York City',
  'New Zealand',
  'Newfoundland and Labrador',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North America',
  'North Carolina',
  'North Dakota',
  'North Sea',
  'Northern Ireland',
  'Northern Territory',
  'Northwest Territories',
  'Northwestern United States',
  'Norway',
  'Nova Scotia',
  'Nunavut',
  'Oceania',
  'Oceans and Seas',
  'Ohio',
  'Oklahoma',
  'Oman',
  'Ontario',
  'Oregon',
  'Ottoman Empire',
  'Pacific Islands',
  'Pacific Ocean',
  'Pacific States',
  'Pakistan',
  'Palau',
  'Panama',
  'Panama Canal Zone',
  'Papua New Guinea',
  'Paraguay',
  'Paris',
  'Pennsylvania',
  'Persia',
  'Peru',
  'Philadelphia',
  'Philippines',
  'Pitcairn Island',
  'Poland',
  'Polynesia',
  'Portugal',
  'Prince Edward Island',
  'Prussia',
  'Puerto Rico',
  'Qatar',
  'Quebec',
  'Queensland',
  'Republic of Belarus',
  'Republic of Korea',
  'Republic of North Macedonia',
  'Reunion',
  'Rhode Island',
  'Romania',
  'Rome',
  'Russia',
  'Russia (Pre-1917)',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Francisco',
  'San Marino',
  'Sao Tome and Principe',
  'Saskatchewan',
  'Saudi Arabia',
  'Scandinavian and Nordic Countries',
  'Scotland',
  'Senegal',
  'Seoul',
  'Serbia',
  'Seychelles',
  'Siberia',
  'Sicily',
  'Sierra Leone',
  'Sikkim',
  'Singapore',
  'Sint Maarten',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Africa',
  'South America',
  'South Australia',
  'South Carolina',
  'South Dakota',
  'South Sudan',
  'Southeastern United States',
  'Southwestern United States',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Tasmania',
  'Tatarstan',
  'Tennessee',
  'Texas',
  'Thailand',
  'Tibet',
  'Timor-Leste',
  'Togo',
  'Tokyo',
  'Tonga',
  'Transcaucasia',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Virgin Islands',
  'Uruguay',
  'USSR',
  'Utah',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vermont',
  'Victoria',
  'Vietnam',
  'Virginia',
  'Wales',
  'Washington',
  'West Indies',
  'West Virginia',
  'Western Australia',
  'Wisconsin',
  'Wyoming',
  'Yemen',
  'Yugoslavia',
  'Yukon Territory',
  'Zambia',
  'Zimbabwe',
] as const;

const MESH_GEOGRAPHIC_DESCRIPTOR_KEYS: ReadonlySet<string> = new Set(
  MESH_GEOGRAPHIC_DESCRIPTOR_NAMES.map(meshTermKey),
);

function meshTermKey(term: string): string {
  return term.replace(/\s+/g, ' ').trim().toLowerCase();
}

export function isMeshGeographicDescriptor(term: string): boolean {
  return MESH_GEOGRAPHIC_DESCRIPTOR_KEYS.has(meshTermKey(term));
}

export function withoutMeshGeographicDescriptors(terms: readonly string[]): string[] {
  return terms.filter((term) => !isMeshGeographicDescriptor(term));
}

const MESH_INDEXED_PROFILE_HOSTS: ReadonlySet<string> = new Set([
  'medicine.yale.edu',
  'ysph.yale.edu',
]);

export function isMeshIndexedProfileUrl(url: string): boolean {
  try {
    return MESH_INDEXED_PROFILE_HOSTS.has(new URL(url).hostname.toLowerCase());
  } catch {
    return false;
  }
}

function researchAreaProvenanceSourceUrl(fieldProvenance: unknown): string {
  if (!fieldProvenance || typeof fieldProvenance !== 'object') return '';
  const entry = (fieldProvenance as Record<string, unknown>).researchAreas;
  if (!entry || typeof entry !== 'object') return '';
  const sourceUrl = (entry as Record<string, unknown>).sourceUrl;
  return typeof sourceUrl === 'string' ? sourceUrl : '';
}

// Serve-time as well as ingest-time, because a stored list whose every entry is a place
// has no successor observation to supersede it once the lanes stop emitting one.
export function withoutMeshSourcedGeographicResearchAreas(
  areas: readonly string[],
  fieldProvenance: unknown,
): string[] {
  if (!isMeshIndexedProfileUrl(researchAreaProvenanceSourceUrl(fieldProvenance))) {
    return areas as string[];
  }
  const kept = areas.filter(
    (area) => typeof area !== 'string' || !isMeshGeographicDescriptor(area),
  );
  return kept.length === areas.length ? (areas as string[]) : kept;
}
