// Research Areas organized by field with colors
// Each field has a unique color for visual identification

enum ResearchField {
  COMPUTING_AI = "Computing & Artificial Intelligence",
  LIFE_SCIENCES = "Life Sciences & Biology",
  PHYSICAL_SCIENCES = "Physical Sciences & Engineering",
  HEALTH_MEDICINE = "Health & Medicine",
  SOCIAL_SCIENCES = "Social Sciences",
  HUMANITIES_ARTS = "Humanities & Arts",
  ENVIRONMENTAL = "Environmental Sciences",
  ECONOMICS = "Economics",
  MATHEMATICS = "Mathematics"
}

// Color mappings for each field
const fieldColors: Record<ResearchField, { bg: string; text: string; border: string }> = {
  [ResearchField.COMPUTING_AI]: { bg: "bg-blue-200", text: "text-blue-800", border: "border-blue-300" },
  [ResearchField.LIFE_SCIENCES]: { bg: "bg-green-200", text: "text-green-800", border: "border-green-300" },
  [ResearchField.PHYSICAL_SCIENCES]: { bg: "bg-yellow-200", text: "text-yellow-800", border: "border-yellow-300" },
  [ResearchField.HEALTH_MEDICINE]: { bg: "bg-red-200", text: "text-red-800", border: "border-red-300" },
  [ResearchField.SOCIAL_SCIENCES]: { bg: "bg-purple-200", text: "text-purple-800", border: "border-purple-300" },
  [ResearchField.HUMANITIES_ARTS]: { bg: "bg-pink-200", text: "text-pink-800", border: "border-pink-300" },
  [ResearchField.ENVIRONMENTAL]: { bg: "bg-teal-200", text: "text-teal-800", border: "border-teal-300" },
  [ResearchField.ECONOMICS]: { bg: "bg-orange-200", text: "text-orange-800", border: "border-orange-300" },
  [ResearchField.MATHEMATICS]: { bg: "bg-indigo-200", text: "text-indigo-800", border: "border-indigo-300" }
};

interface ResearchArea {
  name: string;
  field: ResearchField;
}

// Default research areas - 500+ phrases organized by field
const defaultResearchAreas: ResearchArea[] = [
  // ============================================
  // COMPUTING & ARTIFICIAL INTELLIGENCE (80+)
  // ============================================
  { name: "Artificial Intelligence", field: ResearchField.COMPUTING_AI },
  { name: "Machine Learning", field: ResearchField.COMPUTING_AI },
  { name: "Deep Learning", field: ResearchField.COMPUTING_AI },
  { name: "Neural Networks", field: ResearchField.COMPUTING_AI },
  { name: "Natural Language Processing", field: ResearchField.COMPUTING_AI },
  { name: "Computer Vision", field: ResearchField.COMPUTING_AI },
  { name: "Robotics", field: ResearchField.COMPUTING_AI },
  { name: "Reinforcement Learning", field: ResearchField.COMPUTING_AI },
  { name: "Data Mining", field: ResearchField.COMPUTING_AI },
  { name: "Big Data Analytics", field: ResearchField.COMPUTING_AI },
  { name: "Cloud Computing", field: ResearchField.COMPUTING_AI },
  { name: "Distributed Systems", field: ResearchField.COMPUTING_AI },
  { name: "Cybersecurity", field: ResearchField.COMPUTING_AI },
  { name: "Cryptography", field: ResearchField.COMPUTING_AI },
  { name: "Blockchain", field: ResearchField.COMPUTING_AI },
  { name: "Quantum Computing", field: ResearchField.COMPUTING_AI },
  { name: "Human-Computer Interaction", field: ResearchField.COMPUTING_AI },
  { name: "Software Engineering", field: ResearchField.COMPUTING_AI },
  { name: "Algorithm Design", field: ResearchField.COMPUTING_AI },
  { name: "Computational Complexity", field: ResearchField.COMPUTING_AI },
  { name: "Programming Languages", field: ResearchField.COMPUTING_AI },
  { name: "Computer Graphics", field: ResearchField.COMPUTING_AI },
  { name: "Virtual Reality", field: ResearchField.COMPUTING_AI },
  { name: "Augmented Reality", field: ResearchField.COMPUTING_AI },
  { name: "Internet of Things", field: ResearchField.COMPUTING_AI },
  { name: "Edge Computing", field: ResearchField.COMPUTING_AI },
  { name: "Database Systems", field: ResearchField.COMPUTING_AI },
  { name: "Information Retrieval", field: ResearchField.COMPUTING_AI },
  { name: "Knowledge Graphs", field: ResearchField.COMPUTING_AI },
  { name: "Semantic Web", field: ResearchField.COMPUTING_AI },
  { name: "Speech Recognition", field: ResearchField.COMPUTING_AI },
  { name: "Text Mining", field: ResearchField.COMPUTING_AI },
  { name: "Sentiment Analysis", field: ResearchField.COMPUTING_AI },
  { name: "Recommender Systems", field: ResearchField.COMPUTING_AI },
  { name: "Autonomous Systems", field: ResearchField.COMPUTING_AI },
  { name: "Multi-Agent Systems", field: ResearchField.COMPUTING_AI },
  { name: "Swarm Intelligence", field: ResearchField.COMPUTING_AI },
  { name: "Evolutionary Computation", field: ResearchField.COMPUTING_AI },
  { name: "Genetic Algorithms", field: ResearchField.COMPUTING_AI },
  { name: "Fuzzy Logic", field: ResearchField.COMPUTING_AI },
  { name: "Expert Systems", field: ResearchField.COMPUTING_AI },
  { name: "Cognitive Computing", field: ResearchField.COMPUTING_AI },
  { name: "Neuromorphic Computing", field: ResearchField.COMPUTING_AI },
  { name: "Parallel Computing", field: ResearchField.COMPUTING_AI },
  { name: "High-Performance Computing", field: ResearchField.COMPUTING_AI },
  { name: "GPU Computing", field: ResearchField.COMPUTING_AI },
  { name: "Network Security", field: ResearchField.COMPUTING_AI },
  { name: "Privacy-Preserving Computing", field: ResearchField.COMPUTING_AI },
  { name: "Federated Learning", field: ResearchField.COMPUTING_AI },
  { name: "Transfer Learning", field: ResearchField.COMPUTING_AI },
  { name: "Meta-Learning", field: ResearchField.COMPUTING_AI },
  { name: "Few-Shot Learning", field: ResearchField.COMPUTING_AI },
  { name: "Zero-Shot Learning", field: ResearchField.COMPUTING_AI },
  { name: "Generative AI", field: ResearchField.COMPUTING_AI },
  { name: "Large Language Models", field: ResearchField.COMPUTING_AI },
  { name: "Transformer Models", field: ResearchField.COMPUTING_AI },
  { name: "Convolutional Neural Networks", field: ResearchField.COMPUTING_AI },
  { name: "Recurrent Neural Networks", field: ResearchField.COMPUTING_AI },
  { name: "Graph Neural Networks", field: ResearchField.COMPUTING_AI },
  { name: "Attention Mechanisms", field: ResearchField.COMPUTING_AI },
  { name: "Self-Supervised Learning", field: ResearchField.COMPUTING_AI },
  { name: "Unsupervised Learning", field: ResearchField.COMPUTING_AI },
  { name: "Supervised Learning", field: ResearchField.COMPUTING_AI },
  { name: "Semi-Supervised Learning", field: ResearchField.COMPUTING_AI },
  { name: "Active Learning", field: ResearchField.COMPUTING_AI },
  { name: "Online Learning", field: ResearchField.COMPUTING_AI },
  { name: "Explainable AI", field: ResearchField.COMPUTING_AI },
  { name: "AI Ethics", field: ResearchField.COMPUTING_AI },
  { name: "Fairness in ML", field: ResearchField.COMPUTING_AI },
  { name: "Adversarial Machine Learning", field: ResearchField.COMPUTING_AI },
  { name: "Robust Machine Learning", field: ResearchField.COMPUTING_AI },
  { name: "AutoML", field: ResearchField.COMPUTING_AI },
  { name: "Neural Architecture Search", field: ResearchField.COMPUTING_AI },
  { name: "Model Compression", field: ResearchField.COMPUTING_AI },
  { name: "Knowledge Distillation", field: ResearchField.COMPUTING_AI },
  { name: "Embedded AI", field: ResearchField.COMPUTING_AI },
  { name: "TinyML", field: ResearchField.COMPUTING_AI },
  { name: "MLOps", field: ResearchField.COMPUTING_AI },
  { name: "Computer Architecture", field: ResearchField.COMPUTING_AI },
  { name: "Operating Systems", field: ResearchField.COMPUTING_AI },
  { name: "Compilers", field: ResearchField.COMPUTING_AI },
  { name: "Formal Methods", field: ResearchField.COMPUTING_AI },
  { name: "Software Verification", field: ResearchField.COMPUTING_AI },
  { name: "Program Analysis", field: ResearchField.COMPUTING_AI },

  // ============================================
  // MATHEMATICS (60+)
  // ============================================
  { name: "Pure Mathematics", field: ResearchField.MATHEMATICS },
  { name: "Applied Mathematics", field: ResearchField.MATHEMATICS },
  { name: "Set Theory", field: ResearchField.MATHEMATICS },
  { name: "Combinatorics", field: ResearchField.MATHEMATICS },
  { name: "Graph Theory", field: ResearchField.MATHEMATICS },
  { name: "Number Theory", field: ResearchField.MATHEMATICS },
  { name: "Algebraic Number Theory", field: ResearchField.MATHEMATICS },
  { name: "Analytic Number Theory", field: ResearchField.MATHEMATICS },
  { name: "Abstract Algebra", field: ResearchField.MATHEMATICS },
  { name: "Linear Algebra", field: ResearchField.MATHEMATICS },
  { name: "Group Theory", field: ResearchField.MATHEMATICS },
  { name: "Ring Theory", field: ResearchField.MATHEMATICS },
  { name: "Field Theory", field: ResearchField.MATHEMATICS },
  { name: "Commutative Algebra", field: ResearchField.MATHEMATICS },
  { name: "Homological Algebra", field: ResearchField.MATHEMATICS },
  { name: "Category Theory", field: ResearchField.MATHEMATICS },
  { name: "Topology", field: ResearchField.MATHEMATICS },
  { name: "Algebraic Topology", field: ResearchField.MATHEMATICS },
  { name: "Differential Topology", field: ResearchField.MATHEMATICS },
  { name: "Geometric Topology", field: ResearchField.MATHEMATICS },
  { name: "Algebraic Geometry", field: ResearchField.MATHEMATICS },
  { name: "Differential Geometry", field: ResearchField.MATHEMATICS },
  { name: "Riemannian Geometry", field: ResearchField.MATHEMATICS },
  { name: "Symplectic Geometry", field: ResearchField.MATHEMATICS },
  { name: "Real Analysis", field: ResearchField.MATHEMATICS },
  { name: "Complex Analysis", field: ResearchField.MATHEMATICS },
  { name: "Functional Analysis", field: ResearchField.MATHEMATICS },
  { name: "Harmonic Analysis", field: ResearchField.MATHEMATICS },
  { name: "Fourier Analysis", field: ResearchField.MATHEMATICS },
  { name: "Measure Theory", field: ResearchField.MATHEMATICS },
  { name: "Probability Theory", field: ResearchField.MATHEMATICS },
  { name: "Stochastic Processes", field: ResearchField.MATHEMATICS },
  { name: "Statistics", field: ResearchField.MATHEMATICS },
  { name: "Mathematical Statistics", field: ResearchField.MATHEMATICS },
  { name: "Bayesian Statistics", field: ResearchField.MATHEMATICS },
  { name: "Time Series Analysis", field: ResearchField.MATHEMATICS },
  { name: "Differential Equations", field: ResearchField.MATHEMATICS },
  { name: "Ordinary Differential Equations", field: ResearchField.MATHEMATICS },
  { name: "Partial Differential Equations", field: ResearchField.MATHEMATICS },
  { name: "Dynamical Systems", field: ResearchField.MATHEMATICS },
  { name: "Chaos Theory", field: ResearchField.MATHEMATICS },
  { name: "Numerical Analysis", field: ResearchField.MATHEMATICS },
  { name: "Numerical Methods", field: ResearchField.MATHEMATICS },
  { name: "Computational Mathematics", field: ResearchField.MATHEMATICS },
  { name: "Mathematical Modeling", field: ResearchField.MATHEMATICS },
  { name: "Mathematical Physics", field: ResearchField.MATHEMATICS },
  { name: "Mathematical Logic", field: ResearchField.MATHEMATICS },
  { name: "Proof Theory", field: ResearchField.MATHEMATICS },
  { name: "Model Theory", field: ResearchField.MATHEMATICS },
  { name: "Computability Theory", field: ResearchField.MATHEMATICS },
  { name: "Discrete Mathematics", field: ResearchField.MATHEMATICS },
  { name: "Enumerative Combinatorics", field: ResearchField.MATHEMATICS },
  { name: "Extremal Combinatorics", field: ResearchField.MATHEMATICS },
  { name: "Probabilistic Combinatorics", field: ResearchField.MATHEMATICS },
  { name: "Coding Theory", field: ResearchField.MATHEMATICS },
  { name: "Information Theory", field: ResearchField.MATHEMATICS },
  { name: "Cryptographic Mathematics", field: ResearchField.MATHEMATICS },
  { name: "Representation Theory", field: ResearchField.MATHEMATICS },
  { name: "Lie Theory", field: ResearchField.MATHEMATICS },
  { name: "Operator Theory", field: ResearchField.MATHEMATICS },
  { name: "Spectral Theory", field: ResearchField.MATHEMATICS },
  { name: "Approximation Theory", field: ResearchField.MATHEMATICS },
  { name: "Convex Analysis", field: ResearchField.MATHEMATICS },
  { name: "Variational Analysis", field: ResearchField.MATHEMATICS },
  { name: "Calculus of Variations", field: ResearchField.MATHEMATICS },

  // ============================================
  // LIFE SCIENCES & BIOLOGY (80+)
  // ============================================
  { name: "Genetics", field: ResearchField.LIFE_SCIENCES },
  { name: "Genomics", field: ResearchField.LIFE_SCIENCES },
  { name: "Proteomics", field: ResearchField.LIFE_SCIENCES },
  { name: "Metabolomics", field: ResearchField.LIFE_SCIENCES },
  { name: "Transcriptomics", field: ResearchField.LIFE_SCIENCES },
  { name: "Epigenetics", field: ResearchField.LIFE_SCIENCES },
  { name: "Molecular Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Cell Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Developmental Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Evolutionary Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Systems Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Synthetic Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Biochemistry", field: ResearchField.LIFE_SCIENCES },
  { name: "Biophysics", field: ResearchField.LIFE_SCIENCES },
  { name: "Structural Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Microbiology", field: ResearchField.LIFE_SCIENCES },
  { name: "Virology", field: ResearchField.LIFE_SCIENCES },
  { name: "Bacteriology", field: ResearchField.LIFE_SCIENCES },
  { name: "Mycology", field: ResearchField.LIFE_SCIENCES },
  { name: "Parasitology", field: ResearchField.LIFE_SCIENCES },
  { name: "Immunology", field: ResearchField.LIFE_SCIENCES },
  { name: "Neuroscience", field: ResearchField.LIFE_SCIENCES },
  { name: "Cognitive Neuroscience", field: ResearchField.LIFE_SCIENCES },
  { name: "Computational Neuroscience", field: ResearchField.LIFE_SCIENCES },
  { name: "Neuroimaging", field: ResearchField.LIFE_SCIENCES },
  { name: "Neurobiology", field: ResearchField.LIFE_SCIENCES },
  { name: "Neurophysiology", field: ResearchField.LIFE_SCIENCES },
  { name: "Neurogenetics", field: ResearchField.LIFE_SCIENCES },
  { name: "Botany", field: ResearchField.LIFE_SCIENCES },
  { name: "Plant Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Plant Genetics", field: ResearchField.LIFE_SCIENCES },
  { name: "Plant Physiology", field: ResearchField.LIFE_SCIENCES },
  { name: "Zoology", field: ResearchField.LIFE_SCIENCES },
  { name: "Animal Behavior", field: ResearchField.LIFE_SCIENCES },
  { name: "Ethology", field: ResearchField.LIFE_SCIENCES },
  { name: "Entomology", field: ResearchField.LIFE_SCIENCES },
  { name: "Ornithology", field: ResearchField.LIFE_SCIENCES },
  { name: "Marine Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Aquatic Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Ecology", field: ResearchField.LIFE_SCIENCES },
  { name: "Population Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Conservation Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Biodiversity", field: ResearchField.LIFE_SCIENCES },
  { name: "Bioinformatics", field: ResearchField.LIFE_SCIENCES },
  { name: "Computational Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Biostatistics", field: ResearchField.LIFE_SCIENCES },
  { name: "Phylogenetics", field: ResearchField.LIFE_SCIENCES },
  { name: "Population Genetics", field: ResearchField.LIFE_SCIENCES },
  { name: "Quantitative Genetics", field: ResearchField.LIFE_SCIENCES },
  { name: "Gene Expression", field: ResearchField.LIFE_SCIENCES },
  { name: "Gene Regulation", field: ResearchField.LIFE_SCIENCES },
  { name: "CRISPR", field: ResearchField.LIFE_SCIENCES },
  { name: "Gene Editing", field: ResearchField.LIFE_SCIENCES },
  { name: "Gene Therapy", field: ResearchField.LIFE_SCIENCES },
  { name: "Stem Cell Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Regenerative Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Tissue Engineering", field: ResearchField.LIFE_SCIENCES },
  { name: "Bioengineering", field: ResearchField.LIFE_SCIENCES },
  { name: "Biotechnology", field: ResearchField.LIFE_SCIENCES },
  { name: "Protein Engineering", field: ResearchField.LIFE_SCIENCES },
  { name: "Enzyme Engineering", field: ResearchField.LIFE_SCIENCES },
  { name: "Metabolic Engineering", field: ResearchField.LIFE_SCIENCES },
  { name: "Fermentation", field: ResearchField.LIFE_SCIENCES },
  { name: "Biomaterials", field: ResearchField.LIFE_SCIENCES },
  { name: "Biomechanics", field: ResearchField.LIFE_SCIENCES },
  { name: "Chronobiology", field: ResearchField.LIFE_SCIENCES },
  { name: "Circadian Rhythms", field: ResearchField.LIFE_SCIENCES },
  { name: "Aging Research", field: ResearchField.LIFE_SCIENCES },
  { name: "Longevity", field: ResearchField.LIFE_SCIENCES },
  { name: "Senescence", field: ResearchField.LIFE_SCIENCES },
  { name: "Apoptosis", field: ResearchField.LIFE_SCIENCES },
  { name: "Cell Signaling", field: ResearchField.LIFE_SCIENCES },
  { name: "Signal Transduction", field: ResearchField.LIFE_SCIENCES },
  { name: "Membrane Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Organelle Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Cytoskeleton", field: ResearchField.LIFE_SCIENCES },
  { name: "Cell Division", field: ResearchField.LIFE_SCIENCES },
  { name: "Cell Cycle", field: ResearchField.LIFE_SCIENCES },
  { name: "Chromosome Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Telomere Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "RNA Biology", field: ResearchField.LIFE_SCIENCES },
  { name: "Non-coding RNA", field: ResearchField.LIFE_SCIENCES },
  { name: "MicroRNA", field: ResearchField.LIFE_SCIENCES },
  { name: "Single-Cell Analysis", field: ResearchField.LIFE_SCIENCES },

  // ============================================
  // PHYSICAL SCIENCES & ENGINEERING (80+)
  // ============================================
  { name: "Physics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Quantum Physics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Quantum Mechanics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Particle Physics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "High-Energy Physics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Nuclear Physics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Astrophysics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Cosmology", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Astronomy", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Planetary Science", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Condensed Matter Physics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Solid State Physics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Materials Science", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Nanomaterials", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Nanotechnology", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Nanoscience", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Semiconductors", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Photonics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Optics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Laser Physics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Plasma Physics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Fluid Dynamics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Thermodynamics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Statistical Mechanics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Acoustics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Electromagnetics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Organic Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Inorganic Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Physical Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Analytical Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Computational Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Theoretical Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Materials Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Polymer Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Electrochemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Photochemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Catalysis", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Surface Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Supramolecular Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Green Chemistry", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Chemical Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Process Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Reaction Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Mechanical Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Aerospace Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Aerodynamics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Structural Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Civil Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Electrical Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Electronics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Microelectronics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "VLSI Design", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Power Systems", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Control Systems", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Signal Processing", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Communications Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Wireless Communications", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Antenna Design", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "RF Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Nuclear Engineering", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Fusion Energy", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Renewable Energy", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Solar Energy", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Wind Energy", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Energy Storage", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Battery Technology", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Fuel Cells", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Superconductivity", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Magnetism", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Spintronics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Quantum Materials", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "2D Materials", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Graphene", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Metamaterials", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Smart Materials", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Composites", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Ceramics", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Metallurgy", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Corrosion", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Tribology", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Manufacturing", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Additive Manufacturing", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "3D Printing", field: ResearchField.PHYSICAL_SCIENCES },
  { name: "Precision Engineering", field: ResearchField.PHYSICAL_SCIENCES },

  // ============================================
  // HEALTH & MEDICINE (80+)
  // ============================================
  { name: "Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Clinical Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Internal Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Cardiology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Oncology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Cancer Research", field: ResearchField.HEALTH_MEDICINE },
  { name: "Cancer Biology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Tumor Biology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Cancer Immunotherapy", field: ResearchField.HEALTH_MEDICINE },
  { name: "Hematology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Nephrology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Gastroenterology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Hepatology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Pulmonology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Endocrinology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Rheumatology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Infectious Disease", field: ResearchField.HEALTH_MEDICINE },
  { name: "Epidemiology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Public Health", field: ResearchField.HEALTH_MEDICINE },
  { name: "Global Health", field: ResearchField.HEALTH_MEDICINE },
  { name: "Health Policy", field: ResearchField.HEALTH_MEDICINE },
  { name: "Healthcare Systems", field: ResearchField.HEALTH_MEDICINE },
  { name: "Medical Informatics", field: ResearchField.HEALTH_MEDICINE },
  { name: "Digital Health", field: ResearchField.HEALTH_MEDICINE },
  { name: "Telemedicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Precision Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Personalized Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Translational Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Clinical Trials", field: ResearchField.HEALTH_MEDICINE },
  { name: "Drug Discovery", field: ResearchField.HEALTH_MEDICINE },
  { name: "Drug Development", field: ResearchField.HEALTH_MEDICINE },
  { name: "Pharmacology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Pharmacogenomics", field: ResearchField.HEALTH_MEDICINE },
  { name: "Toxicology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Pharmaceutical Sciences", field: ResearchField.HEALTH_MEDICINE },
  { name: "Drug Delivery", field: ResearchField.HEALTH_MEDICINE },
  { name: "Nanomedicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Regenerative Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Stem Cell Therapy", field: ResearchField.HEALTH_MEDICINE },
  { name: "Cell Therapy", field: ResearchField.HEALTH_MEDICINE },
  { name: "Immunotherapy", field: ResearchField.HEALTH_MEDICINE },
  { name: "Vaccine Development", field: ResearchField.HEALTH_MEDICINE },
  { name: "Vaccination", field: ResearchField.HEALTH_MEDICINE },
  { name: "Pathology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Diagnostics", field: ResearchField.HEALTH_MEDICINE },
  { name: "Medical Imaging", field: ResearchField.HEALTH_MEDICINE },
  { name: "Radiology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Nuclear Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Surgery", field: ResearchField.HEALTH_MEDICINE },
  { name: "Minimally Invasive Surgery", field: ResearchField.HEALTH_MEDICINE },
  { name: "Robotic Surgery", field: ResearchField.HEALTH_MEDICINE },
  { name: "Orthopedics", field: ResearchField.HEALTH_MEDICINE },
  { name: "Neurology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Neurosurgery", field: ResearchField.HEALTH_MEDICINE },
  { name: "Psychiatry", field: ResearchField.HEALTH_MEDICINE },
  { name: "Mental Health", field: ResearchField.HEALTH_MEDICINE },
  { name: "Psychology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Neuropsychology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Pediatrics", field: ResearchField.HEALTH_MEDICINE },
  { name: "Geriatrics", field: ResearchField.HEALTH_MEDICINE },
  { name: "Obstetrics", field: ResearchField.HEALTH_MEDICINE },
  { name: "Gynecology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Reproductive Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Fertility", field: ResearchField.HEALTH_MEDICINE },
  { name: "Dermatology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Ophthalmology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Otolaryngology", field: ResearchField.HEALTH_MEDICINE },
  { name: "Dentistry", field: ResearchField.HEALTH_MEDICINE },
  { name: "Oral Health", field: ResearchField.HEALTH_MEDICINE },
  { name: "Nutrition", field: ResearchField.HEALTH_MEDICINE },
  { name: "Dietetics", field: ResearchField.HEALTH_MEDICINE },
  { name: "Obesity Research", field: ResearchField.HEALTH_MEDICINE },
  { name: "Diabetes Research", field: ResearchField.HEALTH_MEDICINE },
  { name: "Metabolic Disorders", field: ResearchField.HEALTH_MEDICINE },
  { name: "Genetic Disorders", field: ResearchField.HEALTH_MEDICINE },
  { name: "Rare Diseases", field: ResearchField.HEALTH_MEDICINE },
  { name: "Autoimmune Diseases", field: ResearchField.HEALTH_MEDICINE },
  { name: "Allergies", field: ResearchField.HEALTH_MEDICINE },
  { name: "Pain Management", field: ResearchField.HEALTH_MEDICINE },
  { name: "Palliative Care", field: ResearchField.HEALTH_MEDICINE },
  { name: "Rehabilitation", field: ResearchField.HEALTH_MEDICINE },
  { name: "Physical Therapy", field: ResearchField.HEALTH_MEDICINE },
  { name: "Sports Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Emergency Medicine", field: ResearchField.HEALTH_MEDICINE },
  { name: "Critical Care", field: ResearchField.HEALTH_MEDICINE },

  // ============================================
  // SOCIAL SCIENCES (70+)
  // ============================================
  { name: "Sociology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Social Psychology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Cognitive Psychology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Developmental Psychology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Clinical Psychology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Behavioral Science", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Political Science", field: ResearchField.SOCIAL_SCIENCES },
  { name: "International Relations", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Public Policy", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Governance", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Democracy Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Electoral Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Political Theory", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Comparative Politics", field: ResearchField.SOCIAL_SCIENCES },
  { name: "American Politics", field: ResearchField.SOCIAL_SCIENCES },
  { name: "European Politics", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Asian Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "African Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Latin American Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Middle Eastern Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Anthropology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Cultural Anthropology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Archaeology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Linguistics", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Sociolinguistics", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Psycholinguistics", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Computational Linguistics", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Education", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Educational Psychology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Education Policy", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Higher Education", field: ResearchField.SOCIAL_SCIENCES },
  { name: "STEM Education", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Learning Sciences", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Educational Technology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Curriculum Development", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Law", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Constitutional Law", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Criminal Justice", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Human Rights", field: ResearchField.SOCIAL_SCIENCES },
  { name: "International Law", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Legal Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Criminology", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Gender Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Womens Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Ethnic Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Race Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Urban Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Rural Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Demography", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Population Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Migration Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Immigration", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Social Work", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Community Development", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Poverty Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Inequality", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Social Movements", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Media Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Communication Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Journalism", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Digital Media", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Social Media", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Information Science", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Library Science", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Science Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Technology Studies", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Science Policy", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Research Methods", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Quantitative Methods", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Qualitative Methods", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Survey Research", field: ResearchField.SOCIAL_SCIENCES },
  { name: "Experimental Design", field: ResearchField.SOCIAL_SCIENCES },

  // ============================================
  // HUMANITIES & ARTS (60+)
  // ============================================
  { name: "History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Ancient History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Medieval History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Modern History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Art History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Music History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Cultural History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Intellectual History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Economic History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Social History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Military History", field: ResearchField.HUMANITIES_ARTS },
  { name: "Philosophy", field: ResearchField.HUMANITIES_ARTS },
  { name: "Ethics", field: ResearchField.HUMANITIES_ARTS },
  { name: "Bioethics", field: ResearchField.HUMANITIES_ARTS },
  { name: "Political Philosophy", field: ResearchField.HUMANITIES_ARTS },
  { name: "Philosophy of Mind", field: ResearchField.HUMANITIES_ARTS },
  { name: "Philosophy of Science", field: ResearchField.HUMANITIES_ARTS },
  { name: "Epistemology", field: ResearchField.HUMANITIES_ARTS },
  { name: "Metaphysics", field: ResearchField.HUMANITIES_ARTS },
  { name: "Logic", field: ResearchField.HUMANITIES_ARTS },
  { name: "Aesthetics", field: ResearchField.HUMANITIES_ARTS },
  { name: "Religious Studies", field: ResearchField.HUMANITIES_ARTS },
  { name: "Theology", field: ResearchField.HUMANITIES_ARTS },
  { name: "Comparative Religion", field: ResearchField.HUMANITIES_ARTS },
  { name: "Literature", field: ResearchField.HUMANITIES_ARTS },
  { name: "Comparative Literature", field: ResearchField.HUMANITIES_ARTS },
  { name: "Literary Theory", field: ResearchField.HUMANITIES_ARTS },
  { name: "Poetry", field: ResearchField.HUMANITIES_ARTS },
  { name: "Fiction", field: ResearchField.HUMANITIES_ARTS },
  { name: "Drama", field: ResearchField.HUMANITIES_ARTS },
  { name: "Creative Writing", field: ResearchField.HUMANITIES_ARTS },
  { name: "Rhetoric", field: ResearchField.HUMANITIES_ARTS },
  { name: "Classics", field: ResearchField.HUMANITIES_ARTS },
  { name: "Classical Studies", field: ResearchField.HUMANITIES_ARTS },
  { name: "Greek Studies", field: ResearchField.HUMANITIES_ARTS },
  { name: "Roman Studies", field: ResearchField.HUMANITIES_ARTS },
  { name: "Art", field: ResearchField.HUMANITIES_ARTS },
  { name: "Visual Arts", field: ResearchField.HUMANITIES_ARTS },
  { name: "Fine Arts", field: ResearchField.HUMANITIES_ARTS },
  { name: "Contemporary Art", field: ResearchField.HUMANITIES_ARTS },
  { name: "Digital Art", field: ResearchField.HUMANITIES_ARTS },
  { name: "Photography", field: ResearchField.HUMANITIES_ARTS },
  { name: "Film Studies", field: ResearchField.HUMANITIES_ARTS },
  { name: "Cinema", field: ResearchField.HUMANITIES_ARTS },
  { name: "Theater", field: ResearchField.HUMANITIES_ARTS },
  { name: "Performance Studies", field: ResearchField.HUMANITIES_ARTS },
  { name: "Dance", field: ResearchField.HUMANITIES_ARTS },
  { name: "Music", field: ResearchField.HUMANITIES_ARTS },
  { name: "Musicology", field: ResearchField.HUMANITIES_ARTS },
  { name: "Music Theory", field: ResearchField.HUMANITIES_ARTS },
  { name: "Ethnomusicology", field: ResearchField.HUMANITIES_ARTS },
  { name: "Composition", field: ResearchField.HUMANITIES_ARTS },
  { name: "Architecture", field: ResearchField.HUMANITIES_ARTS },
  { name: "Design", field: ResearchField.HUMANITIES_ARTS },
  { name: "Graphic Design", field: ResearchField.HUMANITIES_ARTS },
  { name: "Industrial Design", field: ResearchField.HUMANITIES_ARTS },
  { name: "Museum Studies", field: ResearchField.HUMANITIES_ARTS },
  { name: "Cultural Studies", field: ResearchField.HUMANITIES_ARTS },
  { name: "Postcolonial Studies", field: ResearchField.HUMANITIES_ARTS },
  { name: "Digital Humanities", field: ResearchField.HUMANITIES_ARTS },
  { name: "Book History", field: ResearchField.HUMANITIES_ARTS },

  // ============================================
  // ENVIRONMENTAL SCIENCES (50+)
  // ============================================
  { name: "Environmental Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Climate Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Climate Change", field: ResearchField.ENVIRONMENTAL },
  { name: "Climate Modeling", field: ResearchField.ENVIRONMENTAL },
  { name: "Atmospheric Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Meteorology", field: ResearchField.ENVIRONMENTAL },
  { name: "Oceanography", field: ResearchField.ENVIRONMENTAL },
  { name: "Ocean Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Marine Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Hydrology", field: ResearchField.ENVIRONMENTAL },
  { name: "Water Resources", field: ResearchField.ENVIRONMENTAL },
  { name: "Water Quality", field: ResearchField.ENVIRONMENTAL },
  { name: "Geology", field: ResearchField.ENVIRONMENTAL },
  { name: "Geophysics", field: ResearchField.ENVIRONMENTAL },
  { name: "Geochemistry", field: ResearchField.ENVIRONMENTAL },
  { name: "Seismology", field: ResearchField.ENVIRONMENTAL },
  { name: "Volcanology", field: ResearchField.ENVIRONMENTAL },
  { name: "Earth Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Soil Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Paleontology", field: ResearchField.ENVIRONMENTAL },
  { name: "Paleoclimatology", field: ResearchField.ENVIRONMENTAL },
  { name: "Ecosystem Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Landscape Ecology", field: ResearchField.ENVIRONMENTAL },
  { name: "Forest Ecology", field: ResearchField.ENVIRONMENTAL },
  { name: "Forestry", field: ResearchField.ENVIRONMENTAL },
  { name: "Wetlands", field: ResearchField.ENVIRONMENTAL },
  { name: "Wildlife Biology", field: ResearchField.ENVIRONMENTAL },
  { name: "Wildlife Conservation", field: ResearchField.ENVIRONMENTAL },
  { name: "Conservation Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Sustainability", field: ResearchField.ENVIRONMENTAL },
  { name: "Sustainable Development", field: ResearchField.ENVIRONMENTAL },
  { name: "Environmental Policy", field: ResearchField.ENVIRONMENTAL },
  { name: "Environmental Law", field: ResearchField.ENVIRONMENTAL },
  { name: "Environmental Economics", field: ResearchField.ENVIRONMENTAL },
  { name: "Natural Resource Management", field: ResearchField.ENVIRONMENTAL },
  { name: "Land Use", field: ResearchField.ENVIRONMENTAL },
  { name: "Urban Ecology", field: ResearchField.ENVIRONMENTAL },
  { name: "Urban Planning", field: ResearchField.ENVIRONMENTAL },
  { name: "Environmental Engineering", field: ResearchField.ENVIRONMENTAL },
  { name: "Waste Management", field: ResearchField.ENVIRONMENTAL },
  { name: "Pollution Control", field: ResearchField.ENVIRONMENTAL },
  { name: "Air Quality", field: ResearchField.ENVIRONMENTAL },
  { name: "Environmental Toxicology", field: ResearchField.ENVIRONMENTAL },
  { name: "Remote Sensing", field: ResearchField.ENVIRONMENTAL },
  { name: "Geographic Information Systems", field: ResearchField.ENVIRONMENTAL },
  { name: "Geography", field: ResearchField.ENVIRONMENTAL },
  { name: "Cartography", field: ResearchField.ENVIRONMENTAL },
  { name: "Biogeography", field: ResearchField.ENVIRONMENTAL },
  { name: "Agricultural Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Agronomy", field: ResearchField.ENVIRONMENTAL },
  { name: "Crop Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Food Science", field: ResearchField.ENVIRONMENTAL },
  { name: "Food Security", field: ResearchField.ENVIRONMENTAL },

  // ============================================
  // ECONOMICS (50+)
  // ============================================
  { name: "Economics", field: ResearchField.ECONOMICS },
  { name: "Microeconomics", field: ResearchField.ECONOMICS },
  { name: "Macroeconomics", field: ResearchField.ECONOMICS },
  { name: "Behavioral Economics", field: ResearchField.ECONOMICS },
  { name: "Experimental Economics", field: ResearchField.ECONOMICS },
  { name: "Development Economics", field: ResearchField.ECONOMICS },
  { name: "International Economics", field: ResearchField.ECONOMICS },
  { name: "Labor Economics", field: ResearchField.ECONOMICS },
  { name: "Health Economics", field: ResearchField.ECONOMICS },
  { name: "Public Economics", field: ResearchField.ECONOMICS },
  { name: "Financial Economics", field: ResearchField.ECONOMICS },
  { name: "Econometrics", field: ResearchField.ECONOMICS },
  { name: "Game Theory", field: ResearchField.ECONOMICS },
  { name: "Mechanism Design", field: ResearchField.ECONOMICS },
  { name: "Industrial Organization", field: ResearchField.ECONOMICS },
  { name: "Finance", field: ResearchField.ECONOMICS },
  { name: "Corporate Finance", field: ResearchField.ECONOMICS },
  { name: "Investment", field: ResearchField.ECONOMICS },
  { name: "Asset Pricing", field: ResearchField.ECONOMICS },
  { name: "Portfolio Management", field: ResearchField.ECONOMICS },
  { name: "Risk Management", field: ResearchField.ECONOMICS },
  { name: "Banking", field: ResearchField.ECONOMICS },
  { name: "Financial Markets", field: ResearchField.ECONOMICS },
  { name: "FinTech", field: ResearchField.ECONOMICS },
  { name: "Accounting", field: ResearchField.ECONOMICS },
  { name: "Auditing", field: ResearchField.ECONOMICS },
  { name: "Taxation", field: ResearchField.ECONOMICS },
  { name: "Operations Research", field: ResearchField.ECONOMICS },
  { name: "Optimization", field: ResearchField.ECONOMICS },
  { name: "Decision Science", field: ResearchField.ECONOMICS },
  { name: "Monetary Economics", field: ResearchField.ECONOMICS },
  { name: "Monetary Policy", field: ResearchField.ECONOMICS },
  { name: "Fiscal Policy", field: ResearchField.ECONOMICS },
  { name: "Trade Economics", field: ResearchField.ECONOMICS },
  { name: "Agricultural Economics", field: ResearchField.ECONOMICS },
  { name: "Resource Economics", field: ResearchField.ECONOMICS },
  { name: "Energy Economics", field: ResearchField.ECONOMICS },
  { name: "Urban Economics", field: ResearchField.ECONOMICS },
  { name: "Regional Economics", field: ResearchField.ECONOMICS },
  { name: "Political Economy", field: ResearchField.ECONOMICS },
  { name: "Institutional Economics", field: ResearchField.ECONOMICS },
  { name: "Economic History", field: ResearchField.ECONOMICS },
  { name: "Economic Growth", field: ResearchField.ECONOMICS },
  { name: "Economic Development", field: ResearchField.ECONOMICS },
  { name: "Inequality Economics", field: ResearchField.ECONOMICS },
  { name: "Welfare Economics", field: ResearchField.ECONOMICS },
  { name: "Market Design", field: ResearchField.ECONOMICS },
  { name: "Auction Theory", field: ResearchField.ECONOMICS },
  { name: "Contract Theory", field: ResearchField.ECONOMICS },
  { name: "Information Economics", field: ResearchField.ECONOMICS }
];

// Helper functions
function getResearchAreaByName(name: string): ResearchArea | undefined {
  return defaultResearchAreas.find(
    area => area.name.toLowerCase() === name.toLowerCase()
  );
}

export function getColorForResearchArea(name: string, customAreas?: ResearchArea[]): { bg: string; text: string; border: string } {
  // First check default areas
  const defaultArea = getResearchAreaByName(name);
  if (defaultArea) {
    return fieldColors[defaultArea.field];
  }

  // Then check custom areas if provided
  if (customAreas) {
    const customArea = customAreas.find(
      area => area.name.toLowerCase() === name.toLowerCase()
    );
    if (customArea) {
      return fieldColors[customArea.field];
    }
  }

  // Default to gray if not found
  return { bg: "bg-gray-200", text: "text-gray-800", border: "border-gray-300" };
}

