export const MONGO_MEMORY_LAUNCH_BUDGET_MS = 120000;

export const SUITE_SETUP_AFTER_LAUNCH_BUDGET_MS = 60000;

export const HOOK_TIMEOUT_MS = MONGO_MEMORY_LAUNCH_BUDGET_MS + SUITE_SETUP_AFTER_LAUNCH_BUDGET_MS;
